name: Freedom
description: Livrando vidas.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  flutter_snake_navigationbar: ^0.6.1
  badges: ^2.0.2
  http: any
  shimmer: ^2.0.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.1.1
  intl: ^0.17.0
  flutter_easyloading: ^3.0.5
  hive: ^2.2.0
  hive_flutter: ^1.1.0
  google_fonts: ^4.0.3
  google_maps_flutter: ^2.2.5
  flutter_native_splash: ^2.2.19
  geolocator: ^7.7.0
  shared_preferences: ^2.0.20
  flutter_secure_storage: ^8.0.0
  flutter_dotenv: ^5.0.2
  flutter_launcher_icons: ^0.12.0


flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/preto.png"
  android: true
  ios: true
# flutter pub run flutter_native_splash:create

flutter_icons:
  image_path: "assets/images/icon.png"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/iconpng.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^1.1.2
  build_runner: ^2.1.11
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/icon.png
    - assets/images/branco.png
    - assets/images/ilustration/login.png